# Copyright (c) 2025 Martin Pflaum
# This file is part of the pytexmd project, licensed under the MIT License.
#%%
import os
import subprocess
import sys
#sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

# Step 1: Run sphinx-apidoc to generate .rst files
docs_dir = os.path.abspath(".")
source_dir = os.path.abspath("../../pytexmd")  # Path to the source directory
cmd = ['sphinx-apidoc']
cmd.append('-f')
# Add other necessary arguments to the command
cmd.append('-o')
cmd.append(docs_dir)  # Output directory
cmd.append(source_dir)  # Source directory

try:
    res = subprocess.run(cmd, text=True, capture_output=True, check=True)
    print(res)
    print(res.stdout)

except subprocess.CalledProcessError as e:
    print("CalledProcessError: " + str(e))
    print("Error Output: " + e.output)


import os
import re
# Directory containing the generated .rst files
rst_files_directory = r"."
# Read with specific encoding
#
index_basecontent = ""
with open('index.rst', 'r', encoding='utf-8') as file:
    index_basecontent += file.read()
#with open('index_utilities.rst', 'r', encoding='utf-8') as file:
#    index_basecontent += file.read()


# Process each .rst file generated by sphinx-apidoc
for rst_filename in os.listdir(rst_files_directory):
    # Check if the file starts with "pytexmd." and ends with ".rst"
    cond = rst_filename.startswith("pytexmd.") and rst_filename.endswith(".rst")
    #cond = cond or (rst_filename.startswith("index_utilities.") and rst_filename.endswith(".rst"))
    cond = cond or (rst_filename.startswith("index.") and rst_filename.endswith(".rst"))
    #cond = cond or (rst_filename.startswith("examples.") and rst_filename.endswith(".rst"))
    cond = cond or (rst_filename.split(".")[0] in index_basecontent and rst_filename.endswith(".rst"))
    neg_cond = rst_filename == "references.rst"
    
    if cond and not neg_cond:
        print(f"Processing file: {rst_filename}")
        rst_file_path = os.path.join(rst_files_directory, rst_filename)
        
        # Read the file contents
        with open(rst_file_path, "r", encoding="utf-8") as rst_file:
            rst_content = rst_file.read()
        if rst_filename == "pytexmd.rst":
            print("--------------->>>>>>>>>>>>>><running replace pytexmd.rst")
            rst_content = "\n".join(rst_content.split("\n")[2:])

        # Replace "pytexmd.module_name package" with just "module_name"
        rst_content = re.sub(
            r"pytexmd\.(\w+) package\n=+",
            lambda match: f"{match.group(1)}\n{'=' * len(match.group(1))}",
            rst_content
        )
        
        # Remove "pytexmd." prefix from module references
        rst_content = re.sub(
            r"^pytexmd.",  # Matches lines starting with "pytexmd."
            "",                 # Replaces them with an empty string
            rst_content,
            flags=re.MULTILINE  # Enables multi-line matching
        )

        # Remove " module" and " package" suffixes from titles
        rst_content = re.sub(r" module", r"", rst_content)
        rst_content = re.sub(r" package", r"", rst_content)
        
        # Remove "Subpackages" section heading but keep the toctree
        rst_content = re.sub(
            r"Subpackages\n-+\n\n(.. toctree::.*?)(\n\n|$)",
            r"\1\n\n",
            rst_content,
            flags=re.DOTALL
        )
        
        # Remove "Submodules" section heading
        rst_content = re.sub(
            r"Submodules\n-+\n\n",
            "",
            rst_content
        )
        
        # Handle underscores in titles - temporarily replace them
        rst_content = re.sub(
            r"^(.*\_.*(?:\..+)*)\n(=+|-+)$",
            lambda match: f"{match.group(1).replace(r'\_', 'temreplace')}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        rst_content = re.sub(
            r"^(.*_.*(?:\..+)*)\n(=+|-+)$",
            lambda match: f"{match.group(1).replace(r'_', 'temreplace')}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        
        # Simplify module titles by using only the last part of dotted names
        rst_content = re.sub(
            r"^(\w+\.\w+(?:\.\w+)*)\n(=+|-+)$",
            lambda match: f"{match.group(1).split('.')[-1]}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        # Restore underscores as spaces
        rst_content = rst_content.replace("temreplace", " ")
        rst_content = re.sub(    
            r"^(.*)\n(=+|-+)$",
            lambda match: f"{match.group(1).title()}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        
        # Remove "Module contents" section at the end
        rst_content = re.sub(
            r"Module contents\n-+\n\n\.\. automodule:: .*?\n   :members:\n   :undoc-members:\n   :show-inheritance:\n",
            "",
            rst_content,
            flags=re.DOTALL
        )
        _repl = ".. bibliography:: refs.bib\n   :style: plain"
        rst_content = rst_content.replace(_repl,"")
        # Write the updated content back to the file
        with open(rst_file_path, "w", encoding="utf-8") as updated_rst_file:
            updated_rst_file.write(rst_content)


project = 'PyTeXmd'
copyright = '2025, Martin Pflaum'
author = 'Martin Pflaum'
release = '2.1'
html_title = 'PyTeXmd Documentation'
html_short_title = 'pytexmd'

import os
import sys
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
#sys.path.insert(0, os.path.abspath("."))
#sys.path.insert(0, os.path.abspath("../../pytexmd"))
sys.path.insert(0, os.path.abspath(".."))
import shutil
import os
"""
source_dir = "../examples"
target_dir = "."  # Change this to your target path

os.makedirs(target_dir, exist_ok=True)
def create_examples_rst(examples, output_file="examples.rst"):
    with open(output_file, 'w') as f:
        # Write the header
        f.write("Examples\n")
        f.write("=" * len("examples") + "\n\n")
        
        # Write the toctree directive
        f.write(".. toctree::\n")
        
        # Write each example name with proper indentation
        for example in examples:
            f.write(f"    {example}\n")

examples = []
for filename in os.listdir(source_dir):
    if filename.endswith(".ipynb"):
        full_src_path = os.path.join(source_dir, filename)
        full_dst_path = os.path.join(target_dir, filename)
        shutil.copy(full_src_path, full_dst_path)
        examples.append(filename.split(".")[0])  # Store the filename without extension
"""
#create_examples_rst(examples)
# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["sphinx.ext.autodoc",
              "sphinx.ext.autosummary",
              "sphinx.ext.napoleon",
              "sphinx.ext.viewcode",
              "nbsphinx",
              "sphinx.ext.intersphinx",
              "sphinx_copybutton"
              ]

templates_path = ['_templates']
exclude_patterns = []

autosummary_generate = True
autodoc_member_order = 'bysource'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

#html_theme = 'sphinx_rtd_theme'
html_theme = "furo"
html_static_path = ['_static']
"""html_theme_options = {
    "light_logo": "logo_light.svg",
    "dark_logo": "logo_dark.svg",
    "sidebar_hide_name": True,
}
"""
#bibtex_bibfiles = ['refs.bib']

nbsphinx_allow_errors = True
nbsphinx_execute = 'never'
#html_favicon = "_static/partial.svg"

# Exclude certain notebooks from processing
nbsphinx_execute_arguments = [
    "--InlineBackend.figure_formats={'svg', 'pdf'}",
    "--InlineBackend.rc={'figure.dpi': 96}",
]
