"""Sphinx documentation utilities for pytexmd.

This module provides functions to create Sphinx documentation structure and configuration files.
"""

__all__ = [
    "load_config_template",
    "create_config_file",
    "create_sphinx_documentation",
    "make_html",
    "generate_custom_types_code",
    "DEFAULT_MATHJAX_MACROS",
]

import os
from pprint import pformat
import sys
from pathlib import Path
import subprocess
import time
from typing import Optional
from sphinx.cmd.quickstart import main as sphinx_quickstart
from sphinx.cmd.build import main as sphinx_build


DEFAULT_MATHJAX_MACROS = {
    "ltortoise": r"\unicode{x3014}",
    "rtortoise": r"\unicode{x3015}",
    "ltsbrak": [r"\mathopen{\ltortoise\mspace{1mu}}", 0],
    "rtsbrak": [r"\mathopen{\mspace{1mu}\rtortoise}", 0],
    "mathbbm": [r"\mathbb{#1}", 1],
    "widebar": [r"\overline{#1}", 1],
    "C": r"\mathbb{C}",
    "H": r"\mathbb{H}",
}


def generate_custom_types_code(custom_types: dict) -> str:
    """Generate sphinx_proof registration code for custom theorem types.

    Args:
        custom_types (dict): Mapping of type_name (str) -> display_name (str).

    Returns:
        str: Python code block to append to conf.py.
    """
    if not custom_types:
        return ""

    lines = [
        "",
        "# Custom theorem types (auto-generated by pytexmd)",
        "import re as _prf_re",
        "import sys as _prf_sys",
        "import types as _prf_types",
        "import sphinx_proof.nodes",
        "import sphinx_proof.proof_type",
        "import sphinx_proof.directive",
        "import sphinx_proof.domain",
        "from docutils import nodes",
        "from sphinx_proof.directive import ElementDirective",
        "",
        "# Create a stable module so pickle can resolve node classes.",
        "_prf_nodes_mod = _prf_types.ModuleType('pytexmd_custom_nodes')",
        "_prf_sys.modules['pytexmd_custom_nodes'] = _prf_nodes_mod",
        "",
    ]

    for name in custom_types:
        directive_cls_name = "".join(word.capitalize() for word in name.split("_")) + "Directive"
        lines += [
            f"class {name}_node(nodes.Admonition, nodes.Element):",
            f"    pass",
            f"{name}_node.__module__ = 'pytexmd_custom_nodes'",
            f"_prf_nodes_mod.{name}_node = {name}_node",
            f"",
            f"class {directive_cls_name}(ElementDirective):",
            f"    name = \"{name}\"",
            f"",
        ]

    lines.append("_CUSTOM_TYPES = {")
    for name in custom_types:
        directive_cls_name = "".join(word.capitalize() for word in name.split("_")) + "Directive"
        lines.append(f"    \"{name}\": ({name}_node, {directive_cls_name}),")
    lines += [
        "}",
        "",
        "for _name, (_node_cls, _directive_cls) in _CUSTOM_TYPES.items():",
        "    sphinx_proof.nodes.NODE_TYPES[_name] = _node_cls",
        "    sphinx_proof.proof_type.PROOF_TYPES[_name] = _directive_cls",
        "    sphinx_proof.directive.DEFAULT_REALTYP_TO_COUNTERTYP[_name] = _name",
        "    sphinx_proof.domain.ProofDomain.directives[_name] = _directive_cls",
        "    _prf_m = _prf_re.search(r'\\d+$', _name)",
        "    prf_realtyp_to_countertyp[_name] = ('theorem' + _prf_m.group()) if _prf_m else 'theorem'",
        "",
        "",
    ]

    lines.append("title_map = {")
    for name, display_name in custom_types.items():
        lines.append(f"    \"{name}\": \"{display_name}\",")
    lines += [
        "}",
        "for elem in prf_realtyp_to_countertyp.keys():",
        "    if elem not in title_map.keys():",
        "        title_map[elem] = elem.title()",
        "",
        "if not hasattr(sphinx_proof.nodes, '_pytexmd_original_depart_enumerable_node'):",
        "    sphinx_proof.nodes._pytexmd_original_depart_enumerable_node = sphinx_proof.nodes.depart_enumerable_node",
        "    sphinx_proof.nodes._pytexmd_original_depart_unenumerable_node = sphinx_proof.nodes.depart_unenumerable_node",
        "_original_depart_enumerable_node = sphinx_proof.nodes._pytexmd_original_depart_enumerable_node",
        "_original_depart_unenumerable_node = sphinx_proof.nodes._pytexmd_original_depart_unenumerable_node",
        "",
        "def _depart_enumerable_node(self, node: sphinx_proof.nodes.Node) -> None:",
        "    countertyp = node.attributes.get(\"countertype\", \"\")",
        "    realtyp = node.attributes.get(\"realtype\", \"\")",
        "    display_name = title_map.get(realtyp, realtyp.title())",
        "    _original_depart_enumerable_node(self, node)",
        "    default_name = realtyp.title()",
        "    if display_name == default_name:",
        "        return",
        "    number = sphinx_proof.nodes.get_node_number(self, node, countertyp)",
        "    if isinstance(self, sphinx_proof.nodes.LaTeXTranslator):",
        "        old_title = f\"{default_name} {number}\"",
        "        new_title = f\"{display_name} {number}\"",
        "    else:",
        "        old_title = f\"{sphinx_proof.nodes._(default_name)} {number} \"",
        "        new_title = f\"{sphinx_proof.nodes._(display_name)} {number} \"",
        "    idx = sphinx_proof.nodes.list_rindex(self.body, old_title)",
        "    self.body[idx] = new_title",
        "",
        "",
        "def _depart_unenumerable_node(self, node: sphinx_proof.nodes.Node) -> None:",
        "    realtyp = node.attributes.get(\"realtype\", \"\")",
        "    display_name = title_map.get(realtyp, realtyp.title())",
        "    _original_depart_unenumerable_node(self, node)",
        "    default_name = realtyp.title()",
        "    if display_name == default_name:",
        "        return",
        "    if isinstance(self, sphinx_proof.nodes.LaTeXTranslator):",
        "        old_title = default_name",
        "        new_title = display_name",
        "    else:",
        "        old_title = f'<span class=\"caption-number\">{sphinx_proof.nodes._(default_name)} </span>'",
        "        new_title = f'<span class=\"caption-number\">{sphinx_proof.nodes._(display_name)} </span>'",
        "    idx = sphinx_proof.nodes.list_rindex(self.body, old_title)",
        "    self.body[idx] = new_title",
        "",
        "# Patch both the nodes module AND sphinx_proof's __init__ namespace.",
        "# sphinx_proof/__init__.py does `from .nodes import depart_enumerable_node`",
        "# which binds the name in its own globals. Sphinx's setup() looks up the name",
        "# there, so patching only sphinx_proof.nodes has no effect.",
        "sphinx_proof.nodes.depart_enumerable_node = _depart_enumerable_node",
        "sphinx_proof.nodes.depart_unenumerable_node = _depart_unenumerable_node",
        "sphinx_proof.depart_enumerable_node = _depart_enumerable_node",
        "sphinx_proof.depart_unenumerable_node = _depart_unenumerable_node",
        "",
        "numfig_format = {",
    ]
    for name, display_name in custom_types.items():
        lines.append(f"    \"{name}\": \"{display_name} %s\",")
    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


def load_config_template() -> str:
    """Load the Sphinx configuration template.

    Returns:
        str: Contents of the configuration template file.
    """
    template_path = Path(__file__).parent / "templates" / "conf.txt"
    with open(template_path, 'r', encoding='utf-8') as file:
        return file.read()
    
def create_config_file(output_dir: str, project_name: str, author: str, version: str,
                       custom_types: dict = None, bib_filenames: list = None,
                       mathjax_macros: dict = None) -> None:
    """Create a Sphinx conf.py configuration file in the source directory.

    Args:
        output_dir (str): Directory where the Sphinx documentation is located.
        project_name (str): Name of the project.
        author (str): Author name.
        version (str): Project version.
        custom_types (dict, optional): Mapping of type_name -> display_name for
            custom theorem environments not built into sphinx_proof. Defaults to None.
        bib_filenames (list, optional): Basenames of bibliography files copied to the
            source folder. Replaces the default ['references.bib'] in bibtex_bibfiles.
        mathjax_macros (dict, optional): MathJax macro definitions. Uses the
            application defaults when omitted.

    Returns:
        None
    """
    try:
        source_dir = Path(output_dir) / "source"
        source_dir.mkdir(parents=True, exist_ok=True)
        config_path = source_dir / "conf.py"
        
        config_template = load_config_template()
        project_literal = repr(project_name)
        author_literal = repr(author)
        version_literal = repr(version)
        config_content = config_template.replace("XXPROJECTXX", project_literal)\
                                        .replace("XXAUTHORSXX", author_literal)\
                                        .replace("XXRELEASEXX", version_literal)\
                                        .replace(
                                            "XXMATHJAXMACROSXX",
                                            pformat(
                                                mathjax_macros
                                                if mathjax_macros is not None
                                                else DEFAULT_MATHJAX_MACROS,
                                                sort_dicts=False,
                                            ),
                                        )

        # Substitute bibtex_bibfiles with the actual copied files.
        bib_list = bib_filenames if bib_filenames else ["references.bib"]
        bib_repr = repr(bib_list)
        config_content = config_content.replace(
            "bibtex_bibfiles = ['references.bib']",
            f"bibtex_bibfiles = {bib_repr}"
        )

        config_content += generate_custom_types_code(custom_types or {})
        
        with open(config_path, 'w', encoding='utf-8') as file:
            file.write(config_content)
        
        print(f"Configuration file created at {config_path}")
    except Exception as e:
        print(f"An error occurred while creating the configuration file: {e}")

def create_sphinx_documentation(
    output_dir: str,
    project_name: str = "My Project",
    author: str = "Author",
    version: str = "1.0"
) -> None:
    """Create a Sphinx documentation structure with source and build folders.

    Args:
        output_dir (str): Directory where the Sphinx documentation will be created.
        project_name (str, optional): Name of the project. Defaults to "My Project".
        author (str, optional): Author name. Defaults to "Author".
        version (str, optional): Project version. Defaults to "1.0".

    Returns:
        None
    """
    if os.path.exists(output_dir):
        # if "{output_dir}/Makefile"
        if os.path.exists(os.path.join(output_dir, "Makefile")):
            print(f"Sphinx documentation already exists at {output_dir}. Skipping creation.")
            return
    # Run sphinx-quickstart with automated answers
    output_dir = os.path.abspath(output_dir)
    
    # The API takes a list of CLI-like args (without the program name)
    sphinx_quickstart([
        output_dir,
        "--release", version,
        "--sep",
        "--project", project_name,
        "--author", author,
        "--makefile",
        "--batchfile",
        "--language", "en",
    ])


    #cmd = f"sphinx-quickstart {output_dir} --sep --project={project_name.replace(" ","_")} --author={author.replace(" ","_")} --release={version.replace(" ","_")} --language=en"
    
    print("waiting 0.5 seconds to let the file system catch up")
    time.sleep(0.5)

    # Delete the auto-generated index.rst file
    try:
        index_rst_path = Path(output_dir) / "source" / "index.rst"
        if index_rst_path.exists():
            index_rst_path.unlink()
            print(f"Deleted auto-generated index.rst file at {index_rst_path}")
    except Exception as e:
        print(f"Warning: Could not delete index.rst: {e}")

    try:
        output_dir = os.path.abspath(output_dir)
        Path(output_dir).mkdir(parents=True)
    except:
        pass
    
    output_dir = os.path.abspath(output_dir)
    create_config_file(output_dir, project_name, author, version)


def make_html(output_dir: str, raise_on_error: bool = False) -> Optional[Path]:
    """Build the Sphinx documentation to HTML format.

    Args:
        output_dir (str): Directory where the Sphinx documentation is located.

    Returns:
        None
    """
    try:
        source_dir = os.path.join(output_dir, "source")
        build_dir = os.path.join(output_dir, "build")
        result = sphinx_build([
            "-M",
            "html",
            source_dir,
            build_dir
        ])
        if result != 0:
            raise RuntimeError(f"Sphinx HTML build failed with exit code {result}")
        print(f"Sphinx documentation built successfully at {build_dir}")
        return Path(build_dir) / "html"
    except Exception as e:
        print(f"An error occurred while building the documentation: {e}")
        if raise_on_error:
            raise
        return None
