"""Sphinx documentation utilities for pytexmd.

This module provides functions to create Sphinx documentation structure and configuration files.
"""

__all__ = [
    "load_config_template",
    "create_config_file",
    "create_sphinx_documentation",
    "make_html",
    "generate_custom_types_code",
]

import os
import sys
from pathlib import Path
import subprocess
import time
from sphinx.cmd.quickstart import main as sphinx_quickstart
from sphinx.cmd.build import main as sphinx_build


def generate_custom_types_code(custom_types: dict) -> str:
    """Generate sphinx_proof registration code for custom theorem types.

    Args:
        custom_types (dict): Mapping of type_name (str) -> display_name (str).

    Returns:
        str: Python code block to append to conf.py.
    """
    if not custom_types:
        return ""

    lines = [
        "",
        "# Custom theorem types (auto-generated by pytexmd)",
        "import sphinx_proof.nodes",
        "import sphinx_proof.proof_type",
        "import sphinx_proof.directive",
        "import sphinx_proof.domain",
        "from docutils import nodes",
        "from sphinx_proof.directive import ElementDirective",
        "",
    ]

    for name in custom_types:
        directive_cls_name = "".join(word.capitalize() for word in name.split("_")) + "Directive"
        lines += [
            f"class {name}_node(nodes.Admonition, nodes.Element):",
            f"    pass",
            f"",
            f"class {directive_cls_name}(ElementDirective):",
            f"    name = \"{name}\"",
            f"",
        ]

    lines.append("_CUSTOM_TYPES = {")
    for name in custom_types:
        directive_cls_name = "".join(word.capitalize() for word in name.split("_")) + "Directive"
        lines.append(f"    \"{name}\": ({name}_node, {directive_cls_name}),")
    lines += [
        "}",
        "",
        "for _name, (_node_cls, _directive_cls) in _CUSTOM_TYPES.items():",
        "    sphinx_proof.nodes.NODE_TYPES[_name] = _node_cls",
        "    sphinx_proof.proof_type.PROOF_TYPES[_name] = _directive_cls",
        "    sphinx_proof.directive.DEFAULT_REALTYP_TO_COUNTERTYP[_name] = _name",
        "    sphinx_proof.domain.ProofDomain.directives[_name] = _directive_cls",
        "    prf_realtyp_to_countertyp[_name] = \"theorem\"",
        "",
        "# Override numfig_format so display names use spaces instead of underscores.",
        "# init_numfig() in sphinx_proof applies config.numfig_format on top of its",
        "# auto-generated dict, so setting these here wins.",
        "numfig_format = {",
    ]
    for name, display_name in custom_types.items():
        lines.append(f"    \"{name}\": \"{display_name} %s\",")
    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


def load_config_template() -> str:
    """Load the Sphinx configuration template.

    Returns:
        str: Contents of the configuration template file.
    """
    template_path = Path(__file__).parent / "templates" / "conf.txt"
    with open(template_path, 'r', encoding='utf-8') as file:
        return file.read()
    
def create_config_file(output_dir: str, project_name: str, author: str, version: str, custom_types: dict = None) -> None:
    """Create a Sphinx conf.py configuration file in the source directory.

    Args:
        output_dir (str): Directory where the Sphinx documentation is located.
        project_name (str): Name of the project.
        author (str): Author name.
        version (str): Project version.
        custom_types (dict, optional): Mapping of type_name -> display_name for
            custom theorem environments not built into sphinx_proof. Defaults to None.

    Returns:
        None
    """
    try:
        source_dir = Path(output_dir) / "source"
        source_dir.mkdir(parents=True, exist_ok=True)
        config_path = source_dir / "conf.py"
        
        config_template = load_config_template()
        config_content = config_template.replace("XXPROJECTXX", project_name)\
                                        .replace("XXAUTHORSXX", author)\
                                        .replace("XXRELEASEXX", version)
        config_content += generate_custom_types_code(custom_types or {})
        
        with open(config_path, 'w', encoding='utf-8') as file:
            file.write(config_content)
        
        print(f"Configuration file created at {config_path}")
    except Exception as e:
        print(f"An error occurred while creating the configuration file: {e}")

def create_sphinx_documentation(
    output_dir: str,
    project_name: str = "My Project",
    author: str = "Author",
    version: str = "1.0"
) -> None:
    """Create a Sphinx documentation structure with source and build folders.

    Args:
        output_dir (str): Directory where the Sphinx documentation will be created.
        project_name (str, optional): Name of the project. Defaults to "My Project".
        author (str, optional): Author name. Defaults to "Author".
        version (str, optional): Project version. Defaults to "1.0".

    Returns:
        None
    """
    if os.path.exists(output_dir):
        # if "{output_dir}/Makefile"
        if os.path.exists(os.path.join(output_dir, "Makefile")):
            print(f"Sphinx documentation already exists at {output_dir}. Skipping creation.")
            return
    # Run sphinx-quickstart with automated answers
    output_dir = os.path.abspath(output_dir)
    
    # The API takes a list of CLI-like args (without the program name)
    sphinx_quickstart([
        output_dir,
        "--release", version,
        "--sep",
        "--project", project_name,
        "--author", author,
        "--makefile",
        "--batchfile",
        "--language", "en",
    ])


    #cmd = f"sphinx-quickstart {output_dir} --sep --project={project_name.replace(" ","_")} --author={author.replace(" ","_")} --release={version.replace(" ","_")} --language=en"
    
    print("waiting 0.5 seconds to let the file system catch up")
    time.sleep(0.5)

    # Delete the auto-generated index.rst file
    try:
        index_rst_path = Path(output_dir) / "source" / "index.rst"
        if index_rst_path.exists():
            index_rst_path.unlink()
            print(f"Deleted auto-generated index.rst file at {index_rst_path}")
    except Exception as e:
        print(f"Warning: Could not delete index.rst: {e}")

    try:
        output_dir = os.path.abspath(output_dir)
        Path(output_dir).mkdir(parents=True)
    except:
        pass
    
    output_dir = os.path.abspath(output_dir)
    create_config_file(output_dir, project_name, author, version)


def make_html(output_dir: str) -> None:
    """Build the Sphinx documentation to HTML format.

    Args:
        output_dir (str): Directory where the Sphinx documentation is located.

    Returns:
        None
    """
    try:
        source_dir = os.path.join(output_dir, "source")
        build_dir = os.path.join(output_dir, "build")
        sphinx_build([
            "-M",
            "html",
            source_dir,
            build_dir
        ])
        print(f"Sphinx documentation built successfully at {build_dir}")
    except Exception as e:
        print(f"An error occurred while building the documentation: {e}")